### ISSUE TITLE
"Grab the Code" button should display the code

### ISSUE THREAD

**Issue by TedGoas** [StackExchange/Stacks#100]
Each email template has a button to grab the code, but it launches a window displaying the rendered email instead of the actual code os you have to `view source` to get the code. Both Hynes and Pawel mentioned this.

This button should be updated to show the source code.

---

Possible solution: I've used [this thing](https://pypi.org/project/githubusercontent/) to do this in other projects. I don't think we have to install anything, only follow the project's `url` conventions.

**Comment by ludwiczakpawel** [comment]
For now, you could simply change URL on those links to something like this: [view-source:https://stackoverflow.design/email/templates/transactional-long.html](`view-source:https://stackoverflow.design/email/templates/transactional-long.html`)

**Comment by aaronshekey** [comment]
You should just be able to link directly to the code on GitHub `https://raw.githubusercontent.com/StackExchange/Stacks/develop/docs/email/templates/transactional-long.html` :v:
