### ISSUE TITLE
Missing variants on `@Svg.Female` icon

### ISSUE THREAD

**Issue by Caster** [StackExchange/Stacks#104]
When browsing the [icons] in Stacks, I noticed that there is an `@Svg.Female` icon that portrays a [Venus symbol]. Now I am not sure why it is in there in the first place, but given that it is there, I expected to also find a [Mars symbol] and possibly some of the other [gender symbols]. I could not find those.

Did I overlook them?  
Are they not needed in Stacks? It might make sense to drop the `@Svg.Female` icon as well then.

I know that this is a sensitive topic, especially recently. It might make sense to avoid that altogether by dropping the icon. On the other hand, there may be a legitimate use for the icon somewhere on Stack Exchange that I am not aware of. Just figured I should bring this to your attention.

  [icons]: https://stackoverflow.design/product/resources/icons#icon-set
  [Venus symbol]: https://en.wikipedia.org/wiki/Venus_symbol
  [Mars symbol]: https://en.wikipedia.org/wiki/Planet_symbols#Mars
  [gender symbols]: https://en.wikipedia.org/wiki/Gender_symbol#Sociology

**Comment by Caster** [comment]
I'm sorry if I overlooked anything in [contributing.md](https://github.com/StackExchange/Stacks/blob/develop/CONTRIBUTING.md) or missed a duplicate issue (I searched before creating a new issue). Can you let me know why you closed this issue, @aaronshekey?

**Comment by aaronshekey** [comment]
We use @Svg.Female in our jobs product to signify female-led companies.

We do not have a product need to create an icon for every gender, nor will we be dropping this icon.

This is not an issue for Stacks. It is an issue for our set of icons which is currently not open source. They are included here to explain how to use the SVG helper within the product.

Sorry for the confusion.
