### ISSUE TITLE
"align-items: start" has mixed support

### ISSUE THREAD

**Issue by abovedave** [StackExchange/Stacks#1119]
Getting a warning using both webpack and vite:

```
WARN  start value has mixed support, consider using flex-start instead 
743|    display: flex;
744|    flex-wrap: wrap;
745|    align-items: start;
   |     ^
746|    color: var(--black-200);
747|    font-size: var(--fs-caption);
```

More info I was able to find:
https://stackoverflow.com/a/50919533/11399923
https://github.com/mozilla/addons/issues/3110

**Comment by dancormier** [comment]
Thanks for catching this @abovedave! Fixed in https://github.com/StackExchange/Stacks/commit/3f150e13423840b577539d71e27dec8e0bc80365
