### ISSUE TITLE
<h> classes in docs <h> with padding + negative margin block links directly underneath

### ISSUE THREAD

**Issue by TedGoas** [StackExchange/Stacks#144]
There's an issue with the `stacks-h3` class having a padding + negative margin, it blocks users from clicking a link in Firefox. It's reproducible when trying to click the Litmus link [on this page](https://stackoverflow.design/email/guidelines/best-practices#testing).

Originally reported [on Twitter](https://twitter.com/MrTurnerj/status/1041290007854510081).

**Comment by TedGoas** [comment]
@hellohynes As (I think) the original author of these docs pages, any idea why we do this on [`<h2>`s](https://github.com/StackExchange/Stacks/blob/develop/docs/assets/css/stacks-documentation.css#L10064) and [`<h3>`s](https://github.com/StackExchange/Stacks/blob/develop/docs/assets/css/stacks-documentation.css#L10069)?

**Comment by TedGoas** [comment]
Agree this is low priority and we could just reword this paragraph.

I wonder if `z-index` could handle this somehow?

* `h* {z-index: 0 or -1;}`?
* `h* + p {z-index: 1;}`?

**Comment by hellohynes** [comment]
What's the issue exactly @TedGoas? I'm not sure what link is getting blocked.

**Comment by hellohynes** [comment]
Nvm. I can't remember why we have a padding-top and margin-top on the headers. Let's remove it and see what happens 😎

**Comment by TedGoas** [comment]
<img width="894" alt="screen shot 2018-09-21 at 2 55 53 pm" src="https://user-images.githubusercontent.com/1172461/45900727-8cdc3100-bdae-11e8-9d56-cc36092aa102.png">

[This page](https://stackoverflow.design/email/guidelines/best-practices#testing) in Firefox.

**Comment by hellohynes** [comment]
padding-top: @su64 + @su24; // Hack for #anchor positioning
    margin-top: -@su64 + -@su24; // Hack for #anchor positioning

It was in there for anchor positioning, but I think we can figure out a better way of doing it now.

**Comment by aaronshekey** [comment]
The issue for me is that the Papercut link works. It's so odd.

**Comment by TedGoas** [comment]
@aaronshekey the blocking area only extends `88px` below the `<h>` tag, so I'm guessing the Litmus link is in that danger zone and the papercut link is not.

**Comment by aaronshekey** [comment]
When flipping the sections, it's always the 2nd to last one that doesn't work. Adding z-index to the link itself doesn't fix it, but I'll try some other options.

**Comment by hellohynes** [comment]
@TedGoas @aaronshekey It's blocking the links from the header below. In this example, the paragraph underneath the headers is really short. It's rare that this happens. Most areas in Stacks have:

 1. A header
 2. Paragraph / description
 3. A table; or
 4. An example;
 5. Something else

It's rare for headers to be so close together. Firefox is blocking the links because of the bottom header's top margin.
