### ISSUE TITLE
Illegal HTML in example on input component page

### ISSUE THREAD

**Issue by balpha** [StackExchange/Stacks#1491]
I just noted in a PR that the author put a `<p>` inside a `<label>` and that that's not legal because labels may only contain phrasing content. The author correctly pointed out that this same issue exists in the Stacks documentation, and [indeed it does](https://stackoverflow.design/product/components/inputs/#base-style).

**Comment by dancormier** [comment]
Thanks for the report @balpha. I've updated the inputs docs page example to have valid markup in [this commit](https://github.com/StackExchange/Stacks/commit/71631ffd832c76d19cb0742d51442b68faf9c46b). It should go live with our next Stacks release.
