### ISSUE TITLE
Standardize action links and menus in tables

### ISSUE THREAD

**Issue by TedGoas** [StackExchange/Stacks#157]
We have a few different ways of designing and coding "Actions" that typically appear in the last column of a table row. Let's come up with a design pattern for:

1. How these buttons appear (button styles, order)
2. When to use a dropdown menu
3. What said menu looks like

---

<img width="857" alt="screen shot 2018-09-27 at 1 55 30 pm" src="https://user-images.githubusercontent.com/1172461/46164891-2dbe6680-c25d-11e8-9370-4828674e167c.png">

---

<img width="866" alt="screen shot 2018-09-27 at 1 55 48 pm" src="https://user-images.githubusercontent.com/1172461/46164897-331bb100-c25d-11e8-97f7-66241a76d072.png">

---

<img width="1047" alt="screen shot 2018-09-27 at 1 56 16 pm" src="https://user-images.githubusercontent.com/1172461/46164900-36af3800-c25d-11e8-9242-5b40b41e1add.png">

**Comment by aaronshekey** [comment]
Closing this now that #605 has shipped.
