### ISSUE TITLE
Long code blocks cause a gap between code and example

### ISSUE THREAD

**Issue by TedGoas** [StackExchange/Stacks#16]
[minor] The `overflow-x` causes a gap between long code blocks and it's example. ⤵

<img width="763" alt="screen shot 2018-05-21 at 5 03 52 pm" src="https://user-images.githubusercontent.com/1172461/40329964-6e57dad6-5d19-11e8-8e69-c1cd90f42d73.png">

**Comment by aaronshekey** [comment]
This was fixed by https://github.com/StackExchange/Stacks/commit/b00adbb795f5f33dfd66d5f36306d73e722ff072
