### ISSUE TITLE
Should table <th>'s be `white-space:no-wrap` by default?

### ISSUE THREAD

**Issue by TedGoas** [StackExchange/Stacks#160]
I've run into a few cases where my `<th>`'s have wrapped. I haven't designed a table where I'd want them to wrap. I can add a `ws-nowrap` to fix the problem, but *should this be the default?* And we use `ws-normal` as the override if we need it?

This isn't a risky change for me. If anything, it would _fix_ tables. cc @UXPiper 

---

![image](https://user-images.githubusercontent.com/1172461/46317441-00492400-c5a1-11e8-94ff-422f2a9568b4.png)
no me gusta

**Comment by UXPiper** [comment]
+1000
