### ISSUE TITLE
Monthly newsletter

### ISSUE THREAD

**Issue by aaronshekey** [StackExchange/Stacks#167]
I'd like to send a newsletter to our Stacks users about once a month sharing the latest components and changes to go in. I'd also like to highlight noteworthy refactors.

Creating and extending our email templates is perfectly documented, but one place I'm fuzzy is _how_ we send the actual email.

What's the best way to send these internally, @TedGoas ?

**Comment by ludwiczakpawel** [comment]
I thought that we don't have any automated internal emails but then I found this: https://dev.stackoverflow.com/email/testing/NewEmployeeTarget.Tester/view – I don't remember if I got one but it definitely exists somewhere in code/database.

Not sure if that's helpful at all, but thought I'll mention it here.

**Comment by TedGoas** [comment]
Anita suggests creating a new mailing list (`stacks-updates@stackoverflow` or something) through IT where folks can manage their own subscription. Then we can mail this list using Iterable (or another ESP if we want), which enables use to send an HTML email.

This sounds logical to me. What do we think?

**Comment by aaronshekey** [comment]
Ok, great, that answers my questions about the actual authoring / sending.

If we go the separate mailing list route, we'd probably want to fork the all engineering list and let people opt out, instead of doing an opt-in. But. Do we want people to be able to opt-out? We could just as easily mail the all engineering list straight away.

I don't think we can over communicate, especially if we send only monthly, and only a digest of what's changed.

**Comment by aaronshekey** [comment]
Took the temperature in Hardcore about this and it seems like we can do 2 things:

1. Send directly to `all-devs` and `all-design`
2. Create a new list that uses those as a starting point.

I think I'd prefer the former since it'll be one less thing to manage?

**Comment by TedGoas** [comment]
No 1. is fine with me. Only thing I don't like is this doesn't give designers and developers a way to opt _out_ and doesn't give anyone else the ability to opt _in_. But given the low volume we'll likely send and that this isn't the only way to know what going on with Stacks, I think it's fine.
