### ISSUE TITLE
Audit and refactor patterns in email templates

### ISSUE THREAD

**Issue by TedGoas** [StackExchange/Stacks#202]
It's a lot to maintain. Even as someone who helped write these, I've had moments where I got lost in the code.

I'd like to remove any duplicate or superfluous inline styles and remove a design pattern or two from the promotional template.

**Comment by aaronshekey** [comment]
Each template is hand coded with some duplication, right? There might be some DRY opportunities here? I bet they could be treated as includes in Jekyll.
