### ISSUE TITLE
AJAX Spinner for bigger containers

### ISSUE THREAD

**Issue by mstum** [StackExchange/Stacks#215]
**Is your feature request related to a problem? Please describe.**
I have a bigger element (e.g., a 400x400 pixel div) that is loading data via AJAX and should display a spinner.

We currently have only a tiny one (18x4 pixels), which looks really weird in a big container. Making the container smaller would look weird, and filling it up with more "Data is loading, please wait..." filler seems awkward.

**Describe the solution you'd like**
A 1:1 aspect ratio .svg that can be scaled to any desired size, and then rotated via CSS (kinda [like this](https://stephanwagner.me/only-css-loading-spinner)) would be great. Also, recoloring it via fill-color so that it works on any container background would be neat.

**Describe alternatives you've considered**
http://ajaxload.info/ => Bar Circle or similar.

**Additional context**
I can give a concrete usage example, but I think that having a scaleable AJAX Spinner is a great addition in any case.

**Comment by balpha** [comment]
As of v0.32.0, `s-spinner` is available: https://stackoverflow.design/product/components/spinner
