### ISSUE TITLE
Create remainder of responsive spacing classes

### ISSUE THREAD

**Issue by TedGoas** [StackExchange/Stacks#218]
**Is your feature request related to a problem? Please describe.**
Only _some_ of the `.p*` and `.m*` classes [are responsive](https://stackoverflow.design/product/base/spacing). When a responsive class doesn't exist, we have to write new CSS.

**Describe the solution you'd like**
Create the remainder of the responsive spacing classes.

**Describe alternatives you've considered**
Writing CSS

**Additional context**
<img width="809" alt="screen shot 2018-12-31 at 1 28 04 pm" src="https://user-images.githubusercontent.com/1172461/50565746-ecc46b00-0cff-11e9-9ad7-df1a23f0b43e.png">

**Comment by aaronshekey** [comment]
Which classes are you looking for, specifically? We've intentionally left off `.sm:m16` to save us some bytes since you can just as easily add `.sm:mt16` `.sm:mr16` etc.

**Comment by TedGoas** [comment]
I was looking for negative margin classes last week, which is what made me create this issue.
