### ISSUE TITLE
Spinner rendering issues on Safari

### ISSUE THREAD

**Issue by aaronshekey** [StackExchange/Stacks#225]
The spinners on Safari look to be cut off in 2 directions, resulting in a circle that's flat on 2 "sides". Oops!

![image](https://user-images.githubusercontent.com/1369864/51272691-6b700800-1990-11e9-8329-0199b8d605c6.png)

**Comment by TedGoas** [comment]
@aaronshekey I don't know that I see this in my version of Safari.
<img width="229" alt="screen shot 2019-01-16 at 4 03 53 pm" src="https://user-images.githubusercontent.com/1172461/51278366-6323c700-19a8-11e9-878b-107798b455d5.png">

**Comment by aaronshekey** [comment]
That's because you're viewing at Retina resolutions.
