### ISSUE TITLE
wb-break-word is not a legal atomic class

### ISSUE THREAD

**Issue by balpha** [StackExchange/Stacks#238]
One of the atomic classes we [offer](https://stackoverflow.design/product/base/typography#layout-classes) is `wb-break-word` for `word-break: break-word`.

The problem is that this is not a thing &ndash; `break-word` is not a legal value for `word-break`. The WebKit(ish) browsers just pretend it is, so it works in some browsers. And our users are [relying on this to work everywhere](https://gh.stackoverflow.com/Core/StackOverflow/pull/1849).

`break-word` *is* a legal value for `word-wrap` (actually `overflow-wrap`, but let's not go there).

We actually do have a `ww-break-word` class for that.

So we have two options:

1. Remove the "illegal" `wb-break-word` class and replace all its uses with `ww-break-word`, or
2. keep it, but change it to mean `word-wrap: break-word;` (basically emulating what the WebKit browsers do, but for all browsers).

**Comment by aaronshekey** [comment]
I'd prefer the first option. Thanks for articulating this. It's been bugging me since the earliest days of Stacks.
