### ISSUE TITLE
.s-modal can be blurry on Internet Explorer 11

### ISSUE THREAD

**Issue by bnickel** [StackExchange/Stacks#244]
**Describe the bug**
Internet Explorer's implementation of `translate3d` results in s-modal--dialog being blurry for many widths of dialogs and browsers.

**To Reproduce**
1. Go to https://stackoverflow.design/product/components/modals in Internet Explorer
2. Click on "Launch example modal"
3. Adjust the browser to various widths

**Expected behavior**
Dialog is always crisp

**Screenshots**

*sometimes crisp*

![screen shot 2019-01-30 at 9 46 31 am](https://user-images.githubusercontent.com/662837/51997442-f7476100-2473-11e9-96a1-0aa5f38c3a8e.png)

*sometimes blurry*

![screen shot 2019-01-30 at 9 43 21 am](https://user-images.githubusercontent.com/662837/51997389-df6fdd00-2473-11e9-978c-6c444c866e74.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Internet Explorer
 - Version 11.253.17763.0

**Additional context**
You can see this on https://stackoverflow.com with the comment flagging dialog.

**Comment by aaronshekey** [comment]
Thanks for finding this one, @bnickel. This one's going to be a whack-a-mole situation, since each browser interprets the positioning and subpixels ever-so-slightly differently. I think we may be able to write some IE11-only CSS here though. 🤔
