### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by aaronshekey** [StackExchange/Stacks#250]
Should we consider hosting browser support on the Stacks site itself, or should we mention it somewhere and link to the canonical meta post? This comes up more than I'd like so it may make sense to host it in our docs.

**Comment by ludwiczakpawel** [comment]
We could do both.

**Comment by aaronshekey** [comment]
This has been codified a bit using [Browserl.ist](https://browserl.ist/?q=last+2+versions%2C+not+ie+%3C+11%2C+not+dead%2C+not+op_mini+all%2C+not+baidu+%3E+0%2C+not+and_ff+%3E+0%2C+not+and_qq+%3E+0%2C+not+kaios+%3E+0%2C+not+op_mob+%3E+0%2C+not+ie_mob+%3E+0%2C+not+and_uc+%3E+0%2C+not+Samsung+%3E+0%2C+not+Android+%3E+0).

The meta post has been updated. Eventually, it'd be amazing to print out what we support based on this configuration and have it live on the Stacks site.

**Comment by aaronshekey** [comment]
https://browsers.stackoverflow.design

**Comment by ludwiczakpawel** [comment]
Thanks, @aaronshekey - that's very helpful.
