### ISSUE TITLE
Signin vs Sign in

### ISSUE THREAD

**Issue by TedGoas** [StackExchange/Stacks#259]
`Signin` (noun) vs `Sign in` (verb)
`Login` (noun) vs `Log in` (verb)

It came up in chat and we should document that adding a space to these types of words changes it's part of speech. Perhaps in **Grammar and Mechanics**?

**Comment by aaronshekey** [comment]
Yes! Thanks for filing this! I think we ought to codify this, for sure. I'll open a PR this week.
