### ISSUE TITLE
Popover JavaScript

### ISSUE THREAD

**Issue by aaronshekey** [StackExchange/Stacks#264]
A spec for Popovers can be found in a [Google doc](https://docs.google.com/document/d/1xji7EeKJjRBEZ0Rkxr_UHmKljh4MvnQzY8o_jRfprrc/edit?usp=sharing).

Some work has been started on this in #283.

**Comment by balpha** [comment]
> Developer will add a data attribute to the top level of the page that will listen to a “spawning” controller.

There's no need to have something at "the top level of the page".

> Developer will add a data attribute to the spawning button

Is this "spawning button" something that is specific to popovers? What behavior exactly is expected from such a button?

> Additional data attributes will be added to determine which direction is preferred

Doesn't the popover's CSS already specify this?

> if the popover is dismissible

If the popover is specified to be dismissible, what behavior does this cause exactly? What causes dismissal? Does dismissal remove or just hide the popover?

> or a tooltip

What's the relationship between at tooltip-ish popover and the "spawning button"?
