### ISSUE TITLE
`.s-sidebarwidget--item` but for `.s-popover`

### ISSUE THREAD

**Issue by bnickel** [StackExchange/Stacks#268]
**Is your feature request related to a problem? Please describe.**

I'm trying to implement the following with Stacks:

![screen shot 2019-02-26 at 3 29 20 pm](https://user-images.githubusercontent.com/662837/53451133-5351c680-39db-11e9-9293-23fbd7e57dbb.png)

I could some one-off atomic stuff here, but:

1. This is a pattern that'll probably get reused a lot.
2. It really looks a lot live like if `.s-popover` and `.s-sidebarwidget` had a baby.

**Describe the solution you'd like**

The same design patterns as `.s-sidebarwidget--item` but in a `.s-popover`.  A formal definition for horizontal separators would be nice too.

**Describe alternatives you've considered**

One-off code, but I'm not sure how I'd handle the theme-specific border-left-color.

**Comment by aaronshekey** [comment]
You know, we actually use variations of this pattern in the left nav, the sidebar, and now here. I wonder if it just becomes completely abstracted into its own thing with an option for right or left 🤔
