### ISSUE TITLE
Add `.f:` for :focus and :focus-within

### ISSUE THREAD

**Issue by bnickel** [StackExchange/Stacks#271]
Pretty much every time I want an element to change an atomic style based on hover, I also want it to change if it was focussed or focussed within.

Eg.

~~~
<!-- subtle danger -->
<button class="s-btn s-btn__muted h:fc-red-600">@Svg.TrashSm</button>

<div class="o30 h:o100">
  <span tabindex="0">
    Something you may not care about because
    you already interacted with it.
  </span>
  <button>You can focus me</button>
</div>
~~~

Being able to add `f:fc-red-600` and `f:o100` would improve the keyboard-only experience.

It could also open the door for recreating `s-input` and `s-btn` focus styles on other elements.

**Comment by aaronshekey** [comment]
This seems doable. I also think we'll want to be able to mimic the focus rings that we have on buttons to any arbitrary element?
