### ISSUE TITLE
Grid IE hack doesn't work in column direction

### ISSUE THREAD

**Issue by balpha** [StackExchange/Stacks#284]
The `flex-basis` grid hack for IE (e.g. [here](https://github.com/StackExchange/Stacks/blob/develop/lib/css/atomic/_stacks-grid.less#L34)) explicitly mentions in the comments that

> Since flex-basis applies in the flow direction, we have to conditionally set the width (default) or height (if a column).

which is absolutely correct -- the problem is that the code doesn't actually do this. It's always using the *width*, even if `flex-direction` is `column`.

(Sidenote: "in the flow direction" in that comment would be more correct as "along the main axis")

**Comment by aaronshekey** [comment]
Closing since we're dropping support for IE11. :v:
