### ISSUE TITLE
Confusing examples in /docs/content/principles.html

### ISSUE THREAD

**Issue by PeterMortensen** [StackExchange/Stacks#285]
I find it confusing that the examples for sub sections *"Exaggeration"* and *"Action-oriented"* are ***identical***. Is it a copy-paste error or is it deliberate?

Also, *"Action-oriented"* may have an incorrect ***header level***.

(Corresponding web page: https://stackoverflow.design/content/principles)

**Comment by TedGoas** [comment]
@PeterMortensen Thanks for catching, indeed looks like it was a copy-paste error.
