### ISSUE TITLE
-apple-trailing-word may not be a reliable way to detect WebKit in future

### ISSUE THREAD

**Issue by smfr** [StackExchange/Stacks#290]
_stacks-spinner.less has:

@supports (-apple-trailing-word: auto) {
            box-shadow: 0 0 0 2px transparent;
}

WebKit is planning to remove support for -apple-trailing-word: https://bugs.webkit.org/show_bug.cgi?id=196525

so this will break at some point.

**Comment by aaronshekey** [comment]
Good looking out! We'll have to detect webkit some other way. Got any ideas of timeline there?
