### ISSUE TITLE
Should we have a section for email composition?

### ISSUE THREAD

**Issue by TedGoas** [StackExchange/Stacks#294]
**Idea**
Omaha Mutual's email design system has [a page dedicated to email composition](http://design.mutualofomaha.com/email/composition/). It details how to write various parts of an email. At Stack, the meta information (preheader, unsubscribe text, etc.) sometimes gets forgotten until the last minute and/or YOLO'd when we realize we need to fill in _something_.

Having a guidelines would 1. help us remember to plan ahead for all this, and 2. give us a framework to work within instead of just "going for it" every time.

Here's what they cover **(I think we should do the ones in bold)**:
- **Subject Line**
- **Preheader**
- **Opt-Out Language**
- Content
- Sender Name and Email
- Reply-To
- Call To Actions _(reference Content section)_
- Links _(reference Content section)_

**Comment by TedGoas** [comment]
~Boooooooooo!~

Oh wait you _did_ this? Where can I see it?

**Comment by aaronshekey** [comment]
That automation is a liar. Just clearing out some stuff we aren’t planning to do right now. ✌️
