### ISSUE TITLE
Add JavaScript to the CodePen template

### ISSUE THREAD

**Issue by bnickel** [StackExchange/Stacks#298]
Right now, the CodePen linked in the the docs includes Stacks CSS but not JavaScript.

Please add `https://unpkg.com/@stackoverflow/stacks/dist/js/stacks.min.js` to the JavaScript tab.

**Comment by aaronshekey** [comment]
Ah, yes! I spaced it! On it.

**Comment by aaronshekey** [comment]
Ok, that Pen should have it ✌️
