### ISSUE TITLE
.s-anchors__visible applies incorrect styles

### ISSUE THREAD

**Issue by aalear** [StackExchange/Stacks#337]
**Describe the bug**

I have the following (simplified) markup:

```
<div class="s-sidebarwidget s-sidebarwidget__yellow s-anchors s-anchors__visited s-anchors__default">
    <div class="s-sidebarwidget--header s-sidebarwidget__small-bold-text">Featured</div>
    <ul class="s-sidebarwidget--content s-sidebarwidget__items pt0 pr16 pb0 pl16">
        <li class="s-sidebarwidget--item grid">
            <div>
                <a href="#">My link</a>
            </div>
        </li>
    </ul>
</div>
```

It looks like wrong colors are applied to the links. Instead of default, I see :visited. Instead of :hover, I see :visited. And visited links aren't styled any differently at all.

**Expected behavior**
What I expect is for the link to be styled with its default color (#055fb7 in this case), for the :hover color (#0679e9) to apply when I hover over it, and for the :visited color (#044585) to apply once I've visited it.

**Screenshots**
Default state:
![image](https://user-images.githubusercontent.com/361657/58909426-146d9400-86e1-11e9-9ca5-28b8b55f7ff5.png)

Hover:
![image](https://user-images.githubusercontent.com/361657/58909434-1b94a200-86e1-11e9-8959-4c13572a3a39.png)

Visited links are shown the same as the default. 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version 74.0.3729.169 (Official Build) (64-bit)

**Comment by aaronshekey** [comment]
Dang, nice bug report. We're on it!
