### ISSUE TITLE
Typos in the JavaScript guidelines page

### ISSUE THREAD

**Issue by arulkumar4** [StackExchange/Stacks#371]
There is a typo in the [JavaScript Guidelines](https://stackoverflow.design/product/guidelines/javascript) page. 

1. Under the [Creating your own Stimulus controllers](https://stackoverflow.design/product/guidelines/javascript#creating-your-own-stimulus-controllers) section, the term "official documentation" is wrongly displaying as "offical documentation". i.e., "i" is missing in the word "official".

Screenshot for reference:

> ![Official](https://user-images.githubusercontent.com/11418896/63414667-f2e79300-c419-11e9-9d57-887e543171fb.png)

2. Also under the [JavaScript classnames](https://stackoverflow.design/product/guidelines/javascript#javascript-classnames) section, the term "component classes" is wrongly displaying as "compononent classes". i.e., extra "on" is added in the "component".

Screenshot for reference:

![iComponent](https://user-images.githubusercontent.com/11418896/63414883-638eaf80-c41a-11e9-8a66-19c8ca7c04d6.png)

Can this be corrected?

**Comment by aaronshekey** [comment]
Fixed! Thanks for finding!
