### ISSUE TITLE
Input font size causes zoom in on mobile devices

### ISSUE THREAD

**Issue by aaronshekey** [StackExchange/Stacks#382]
Since our input / textarea font size is smaller than 16px, when a user interacts with them on mobile, the whole page zooms in.

We should find ways to mitigate this, either making the text size `>= 16px`, or finding a workaround.

**Comment by aaronshekey** [comment]
Here's a good illustration of this issue:

![lame_zoom](https://user-images.githubusercontent.com/1369864/64380964-c1fd8580-cff7-11e9-9e8a-814d52a863ad.gif)

**Comment by brettinternet** [comment]
Here is a [related post in meta](https://meta.stackoverflow.com/questions/389464/form-elements-should-be-at-least-16px-font-size-to-prevent-mobile-browsers-from).

**Comment by aaronshekey** [comment]
Fixed in #383 🤙
