### ISSUE TITLE
Popovers are aligned to subpixels at zoom levels other than 100%

### ISSUE THREAD

**Issue by aaronshekey** [StackExchange/Stacks#392]
As [reported on Meta](https://meta.stackexchange.com/questions/333521/share-box-becomes-blurry-if-not-at-100-zoom-level), it appears that popovers are blurry at various zoom levels.

**Comment by aaronshekey** [comment]
Another report https://meta.stackexchange.com/questions/337797/blurry-text-on-stack-overflow-with-chrome?noredirect=1#comment1123637_337797

**Comment by rschrieken** [comment]
another report https://meta.stackexchange.com/questions/333521/share-box-becomes-blurry-if-not-at-100-zoom-level

**Comment by bnickel** [comment]
This was fixed in https://github.com/popperjs/popper-core/commit/39c3076ef9cb9a3a53621f57de3de56bea8451fd

We should be able to resolve this by upgrading to Popper 2.

**Comment by aaronshekey** [comment]
Well loooook at that. Good looking out! :v:

**Comment by gtsiolis** [comment]
This is no longer reproducible. `@popperjs/core` has been updated to `2.1.1` (https://github.com/StackExchange/Stacks/pull/465), `2.2.0` (https://github.com/StackExchange/Stacks/pull/475), and `2.4.0` (https://github.com/StackExchange/Stacks/pull/495).

**Comment by aaronshekey** [comment]
Nice! I think the last time I had a look at this, there was still some minor zoom stuff happening, but this has definitely stabilized. Closing. Thanks, @gtsiolis!
