### ISSUE TITLE
Links styled as buttons use visited link color for text, making it hard to read

### ISSUE THREAD

**Issue by johnmwright** [StackExchange/Stacks#402]
**Describe the bug**
When using the button styling for a link, the link text color is using the browser default for visited links (dark blue), which makes the text difficult to read on a "primary" button.  It would be preferred for the `.s-btn*` classes to set the font color explicitly so that it behaves like a `<button />` would.

**To Reproduce**
1. create an html link and use the `s-btn` and `s-btn__primary` classes so that it looks like a button:
``` html
<a class="s-btn s-btn__primary" href="https://superusers.com">
    Search All Accounts
</a>
```
2. Click the button to follow the link
3. Note that the button's text is now using the visited link colors

**Expected behavior**
The font color on the "button" styled link will remain the same both before and after the link is followed, preferably white.

**Screenshots**
Before following the link:
![image](https://user-images.githubusercontent.com/3373249/65996398-f3356e00-e45c-11e9-9478-01336760c93a.png)

After following the link:
![2019-10-01_15-07-36](https://user-images.githubusercontent.com/3373249/65996562-41e30800-e45d-11e9-8a34-13634169d95e.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10 Ent
 - Browser Chrome
 - Version  77.0.3865.90

**Comment by aaronshekey** [comment]
This is a great bug report, thanks for filing it. Even a gif?! Nice work.

Unfortunately, I think this is something outside of `Stacks`, likely some overly-specific CSS in `Careers` that is trolling you. If you check out this [Codepen](https://codepen.io/aaronshekey/pen/MWgNayY?editors=1000), you'll see that things are behaving as designed.

**Comment by johnmwright** [comment]
Indeed, you are correct!
This style was hanging around:
``` css
a:visited {
    color: @blue-700;
}
```
