### ISSUE TITLE
Popovers not closing on tap for Safari on iOS

### ISSUE THREAD

**Issue by hamvocke** [StackExchange/Stacks#403]
When using Safari on iOS, popover components don't close when I'm tapping outside of the popover.

This is reproducible as given in this [bug report on meta](https://meta.stackexchange.com/questions/333397/search-bar-s-tooltip-popup-hasn-t-closing-on-tapping-on-many-areas).

Apparently, listening for `click` events alone isn't going to cut it for Safari/iOS. We could enhance our event handling for closing popovers or refrain to [this popular and still relevant hack](https://stackoverflow.com/questions/14795944/jquery-click-events-not-working-in-ios).

**Comment by dancormier** [comment]
Tested on iOS (iPhone XR, iPad 7th gen, iPhone 12 Max via iOS simulator) and this bug seems to be resolved.
Closing this issue in the spirit of spring cleaning.
