### ISSUE TITLE
Component: Input type file

### ISSUE THREAD

**Issue by aaronshekey** [StackExchange/Stacks#435]
We need a way to reliably upload files in a Stacks-styled manner.

**Comment by aaronshekey** [comment]
Additionally, a bite-sized version of this might see us just making this thing official: 
![image](https://user-images.githubusercontent.com/1369864/76987199-c98bd880-6910-11ea-89ff-344d5c74f970.png)

**Comment by dancormier** [comment]
@aaronshekey do you see this input being nested in [`.s-input`](https://stackoverflow.design/product/components/inputs/) or broken out as it's own component?

**Comment by aaronshekey** [comment]
I don't imagine this will be a simple drop-in replacement for `<input type="file">`, since it'll involve JS and drop targets and such. Something like this [Codepen](https://codepen.io/aaronshekey/pen/gOgYVGM) I whipped together? Might look a little familiar to you.

**Comment by dancormier** [comment]
heh, yep I saw that codepen and lifted some here https://codepen.io/dancormier/pen/b6620863c74388704a105516732d3dce?editors=1001

**Comment by aaronshekey** [comment]
To answer more clearly (classic Aaron), I think this'll be a standalone component with Stimulus events and such, with its own `/product/components/uploader` docs page or whatever.
