### ISSUE TITLE
Popovers within fixed parent scroll with page

### ISSUE THREAD

**Issue by aaronshekey** [StackExchange/Stacks#473]
Based on a [report on meta](https://meta.stackoverflow.com/questions/396109/products-menu-in-firefox-scrolls-with-page), this seems isolated to Firefox. May be a regression in how Popper 2 handles positioning?

Steps to reproduce:

1. Load SO on Firefox
2. Open the products popover
3. Scroll

**Comment by aaronshekey** [comment]
A small reproducible example https://codepen.io/aaronshekey/full/GRJeyaY

**Comment by FezVrasta** [comment]
Your issue should be fixed in [@popperjs/core@2.2.0](https://github.com/popperjs/popper-core/releases/tag/v2.2.0)

**Comment by aaronshekey** [comment]
Wow, we're all flipping out that you proactively let us know about this one. I threw a contribution your way. Hopefully I can get something recurring going at the org-level :v:

**Comment by FezVrasta** [comment]
Thanks for the support 🤗
