### ISSUE TITLE
Review form/input styles to make sure they're mobile friendly

### ISSUE THREAD

**Issue by hellohynes** [StackExchange/Stacks#48]
Right now the mobile less has it's own input/form Less files. We should test our current styles to make sure they're mobile friendly as well so we can properly deprecate the mobile skins.

Maybe something @ludwiczakpawel can help within a few weeks?

**Comment by ludwiczakpawel** [comment]
Sure, I could help with that. But TBH I'm not sure if we apply any special treatment to our existing mobile form fields. I can't think of any special case or styling that makes any field behave differently on mobile comparing to desktop. 

Have you thought about anything in particular?

**Comment by aaronshekey** [comment]
Interestingly, mobile safari adds an inner shadow to our inputs that's pretty deep. Might be worth applying `-webkit-appearance: none` in this context if we aren't already.
