### ISSUE TITLE
npx isn't installed by default, causing npm start to fail

### ISSUE THREAD

**Issue by mstum** [StackExchange/Stacks#493]
**Describe the bug**

Running `npm start` after `npm run init-docs`:

```bash
Running "concurrent:serve" (concurrent) task
    Running "watch" task
    Running "shell:eleventyServe" (shell) task
    Waiting...
    Warning: Command failed: npx @11ty/eleventy --serve --incremental
    /bin/sh: 1: npx: not found
     Use --force to continue.

    Aborted due to warnings.
Warning:  Use --force to continue.

Aborted due to warnings.
```

**To Reproduce**

1. Start with a fresh Ubuntu 18.04 Linux or WSL2 Ubuntu 18.04 system
2. apt install npm
3. Clone master
4. `npm run init-docs`
5. `npm start`

**Expected behavior**
Unicorns, rainbows, and a working web server on http://localhost:8080/

**Screenshots**
![image](https://user-images.githubusercontent.com/104127/83366587-144cb680-a37e-11ea-96ed-de827d3e5b1c.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 running on WSL2 in Windows 10 2004

**Additional context**
`npm install -g npx` fixes this - which makes me thing that package.json should have npx as a devDependency or something like that.

**Comment by b-kelly** [comment]
npx is installed by default along with npm@5.2.0 (July 2017!) or greater. I'll try to reproduce given your steps. If Ubuntu 18.04 ships with such an old version by default, we'd need to think about either pinning our node version or adding `npx` to the dev-dependencies as you suggest.

**Comment by mstum** [comment]
The version installed by `apt install npm` is 3.5.2 (and node.js is v8.10.0):

```bash
nodejs/bionic-updates,now 8.10.0~dfsg-2ubuntu0.4 amd64 [installed,automatic]
  evented I/O for V8 javascript

npm/bionic,now 3.5.2-0ubuntu4 all [installed]
  package manager for Node.js
```

Ubuntu 18.04 is pretty old (April 2018), but until just recently it was the latest LTS.

I ran `npm install -g npm` and that installed a separate npm 6.14.5 into /usr/local/bin/npm, but the npm command still resolves to the v3.5.2 that's part of Ubuntu. yeah, it's ancient and it would probably make more sense to install node.js and npm from the official websites instead of the Ubuntu package repository, but, well, apt-get is one default, so if required, maybe guard against old versions of npm being used? (Not sure if that's possible, requiring npm >= 5.2.0)

**Comment by b-kelly** [comment]
Yeah, that's what I figured it was. We can definitely guard against old versions using [engines in package.json](https://docs.npmjs.com/files/package.json#engines), but if the *only* thing broken by the old version is npx, then we can probably make it work. That being said, #494 might be a similar issue, so we probably need to set a lowest supported version.

I'll take a peek at it today.

**Comment by mstum** [comment]
FWIW, I'm ok with "ancient npm is SOL", just wanted to report the experience and let y'all decide how to handle it - error, document, support, shrug - up to you, I'll setup an Ubuntu 20.04 LTS WSL2 as my primary environment.

**Comment by b-kelly** [comment]
Thanks for the report, we love hearing stuff like this. ❤️

**Comment by mstum** [comment]
Just FYI, here's what's default for Ubuntu 20.04 LTS - much better :)

```bash
nodejs/focal 10.19.0~dfsg-3ubuntu1 amd64
  evented I/O for V8 javascript - runtime executable

npm/focal 6.14.4+ds-1ubuntu2 all
  package manager for Node.js
```

**Comment by aaronshekey** [comment]
Is there any follow-up needed here, or can I close this issue?

**Comment by b-kelly** [comment]
Followup is potentially a couple of things:

* remove `npx` from the command (very, very likely that it isn't needed, npm already scopes by default)
* update `package.json` to specify we only support node > x version

I have a free moment, let me drop npx and see if it still runs

**Comment by b-kelly** [comment]
Nope. 🙂 The commands are in `grunt`, not the package.json scripts. I was mistaken on the location. Removing them does *not* work on my machine.

I vote we go ahead and close the issue with an official statement that we only support the latest LTS of node at any point in time for compiling the dev environment. The situation would be a bit different if the version of node affected runtime, but it doesn't for us.
