### ISSUE TITLE
Typescript compilation error: lib/ts/controllers/s-table.ts(4,38): error TS1255: A definite assignment assertion '!' is not permitted in this context.

### ISSUE THREAD

**Issue by mstum** [StackExchange/Stacks#494]
**Describe the bug**
Trying to run `npm start` fails with a Typescript compilation error:

```bash
  Running "ts:stacks_js" (ts) task
        Compiling...
        Using tsc v3.9.3
        lib/ts/controllers/s-table.ts(4,38): error TS1255: A definite assignment assertion '!' is not permitted in this context.
        lib/ts/controllers/s-table.ts(5,39): error TS1255: A definite assignment assertion '!' is not permitted in this context.

        >> 2 syntax errors
        >> Error: tsc return code: 2
        Warning: Task "ts:stacks_js" failed. Use --force to continue.

        Aborted due to warnings.
```

**To Reproduce**
1. Start with a fresh Ubuntu 18.04 Linux or WSL2 Ubuntu 18.04 system
2. apt install npm
3. Clone master
4. `npm run init-docs`
5. `npm start`

**Expected behavior**
Unicorns, rainbows, and a working web server on http://localhost:8080/

**Screenshots**
![image](https://user-images.githubusercontent.com/104127/83366669-92a95880-a37e-11ea-8db6-c5c1082729b0.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 running on WSL2 in Windows 10 2004

**Additional context**
Made it compile by removing the exclamation mark from the file, but I haven't dug into the context to figure out if that's the right fix.

![image](https://user-images.githubusercontent.com/104127/83366683-afde2700-a37e-11ea-9f0d-3e7e570ace05.png)

**Comment by b-kelly** [comment]
Like #493 reported earlier, I have a feeling this might be due to an old node install issue. I'll try to repro with your steps and see if that's not the issue.

**Comment by mstum** [comment]
It seems that it's using a recent typescript - tsc v3.9.3 - so not sure if it might be the opposite issue (code was written for TS 3.7/3.8 but breaks on TS 3.9?)

**Comment by b-kelly** [comment]
There was some discussion a few months ago in our internal Slack that this exact piece code is not really 100% optimal/correct anyways, so maybe I'll take the opportunity to fix it here. 😉

**Comment by mstum** [comment]
I've just setup a brand new Ubuntu 20.04 LTS instance and ran npm start, and for some reason it's using `Using tsc v3.4.1`. I don't know if during my initial testing I somehow got a newer version of TypeScript (the mentioned v3.9.3), but just reporting that the default "clone, npm run init-docs, npm start" works find out of the box, but this error here seems a legitimate error on newer TypeScript versions.

**Comment by aaronshekey** [comment]
Poking at this in a housekeeping branch. Stacks Typescript is currently at `3.4.1`. Bumping to `3.9.5` displays this exact error.

**Comment by b-kelly** [comment]
Just tested locally. Simply removing the `declare`s in `s-table.js` on lines 4 and 5 does the trick. It compiles and works as expected on both the latest version of TS _and_ our current version.

@aaronshekey You want to drop the changes into your housekeeping branch or should I submit a PR?

If we're updating the Typescript version, I'd rather see the `!`s dropped instead ("more correct"), but this strategy throws an error on compile with the current TS version.

**Comment by aaronshekey** [comment]
> You want to drop the changes into your housekeeping branch or should I submit a PR?

@b-kelly I can drop those changes into the housekeeping branch and bump Typescript.
