### ISSUE TITLE
`s-table` border defects with `rowspan`

### ISSUE THREAD

**Issue by bnickel** [StackExchange/Stacks#516]
A minimal example via https://codepen.io/bnickel/pen/BajbQqE:

```html
    <table class="s-table">
        <tr>
            <td>1</td>
            <td rowspan="3">2</td>
        </tr>
        <tr>
            <td>1</td>
        </tr>
        <tr>
            <td>1</td>
        </tr>
    </table>
```

![Screen Shot 2020-07-23 at 1 12 59 PM](https://user-images.githubusercontent.com/662837/88334436-a0c48700-cce6-11ea-9d55-bfad69fd1d7f.png)

There are two distinct issues:

1. The cells in row 2+ of the span that are immediately before the tall cell are one pixel too wide.
2. If the last visible cell in the table does not exist in the last row (due to a rowspan) the wrong cell will have a border radius.  I would assume this is also true of the first cell.

**Comment by aaronshekey** [comment]
Punted table stuff with a revert. Closing for now.
