### ISSUE TITLE
More consistent button vs link selectability

### ISSUE THREAD

**Issue by luap42** [StackExchange/Stacks#540]
**Describe the bug**
Stacks provides support for links and button components. However, not every Stacks button is a HTML `<button>` and not every Stacks link is a HTML `<a href="">`.

Now, this causes inconsistency issues in Firefox. When I have a HTML `<a>`, the element's text can be selected by the user, too. When I have a HTML `<button>`, the element's text cannot be selected by the user. However, this behavior doesn't neccessarily match the styling provided by Stacks.

For example, in the post action button list, the new "follow" link cannot be selected, while all other elements can:

![image showing the aforementioned bug of most but one post actions being user selectable](https://cdn.discordapp.com/attachments/628507458910027777/752977113555927121/unknown.png)

While the use of a `<button>` element is likely correct here, it would be better if the whole thing were consistent.

Furthermore, things that look like buttons are actually links (for example the "Ask Question" btn) and should behave like such.

![image showing the ask question button being selectable](https://cdn.discordapp.com/attachments/628507458910027777/752979341100449973/unknown.png).

This should be consistency-fied. I propose to make

* Stack buttons, that look like buttons, to be `user-select: none`, and
* Stack links, that look like links, to be `user-select: all`.

Buttons that look like buttons are IMHO everything with `.s-btn`, **except** for those with `.s-btn__unset` or `.s-btn__link`. Links that look like links are all links without `.s-btn`.

**Reproduced on desktop Firefox**
 - OS: Windows 10
 - Browser firefox
 - Version 80.0.1 (latest)

**Not an issue on desktop Chrome**

**Comment by aaronshekey** [comment]
Thanks for filing this! Some more consistency here would definitely be nice, just gotta nail the expected behavior and make sure we aren't messing with anyone relying on the existing behavior.

If you're feeling up to it, I would love to see a pull request, but I'd totally understand if you don't have the time :v:

**Comment by luap42** [comment]
@aaronshekey gave it a try. :)
