### ISSUE TITLE
s-navigation should work cleanly when there's a list inside the nav

### ISSUE THREAD

**Issue by benjamin-hodgson** [StackExchange/Stacks#607]
The [MDN docs for `nav`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/nav) have an `ol` inside the `nav`, and each navigation link inside an `li`. [The docs for `s-navigation`](https://stackoverflow.design/product/components/navigation/) omit the list; if I do use a list I have to manually use `list-reset` on the list and `d-inline-block` on the list items. It also breaks `s-navigation__scroll`.

Per [a discussion in chat](https://stackexchange.slack.com/archives/C27RWNQN9/p1615403488108900), it sounds like the version with the list is better for accessibility, so we should at least make sure that works with `s-navigation`, and ideally with minimal additional markup.

**Example**:

```html
<nav class="s-navigation s-navigation__scroll">
    <ol>
        <li><a class="s-navigation--item">Link 1</a></li>
        <li><a class="s-navigation--item">Link 2</a></li>
        <li><a class="s-navigation--item">Link 3</a></li>
    </ol>
</nav>
```

**Expected behaviour**:
1. (Nice-to-have) The nav is styled as a horizontal nav, with no bullets, without having to use `list-reset` on the `ol` and `d-inline-block` on the `li`s. Likewise, `s-navigation__vertical` behaves correctly
2. `s-navigation__scroll`'s overrides work correctly (when container is narrow, items don't wrap to a second line and scrollbar appears).
3. The docs are updated to recommend (or require??) the use of an `ol` or `ul` inside the `nav`.

**Comment by bnickel** [comment]
While more markup isn't always a better accessibility experience, it does seem like both MDN and the W3C both heavily favor putting lists in nav elements as their default configuration, so :+1: on this idea.

I think from a component standpoint, it might make more sense to have:

```
<nav>
    <ol class="s-navigation s-navigation__scroll">
        <li><a class="s-navigation--item">Link 1</a></li>
        <li><a class="s-navigation--item">Link 2</a></li>
        <li><a class="s-navigation--item">Link 3</a></li>
    </ol>
</nav>
```

That would give us a clearer indication that the list itself needs special treatment and we could do something like `ol.s-navigation > li { .super-reset-mixin() }`

We'd also be able to throw whatever styling on the `<nav>` more freely and put a `<h1>` in there or whatever.

**Comment by bnickel** [comment]
It's a shame XHTML 2.0 never caught on with `<li href>`

**Comment by kylejrp** [comment]
+1 on using `nav` > `ul`/`ol` > `li` structure for accessibility

See [Bootstrap's navbar](https://getbootstrap.com/docs/4.3/components/navbar/) component for more ways to semantically structure `<nav>` components, including putting buttons or forms inside a `<nav>`.

**Comment by aaronshekey** [comment]
I don't see a way to do this without introducing breaking changes. Nothing we haven't done before, but it'll require us to babysit any uses of `s-navigation` in production. Happy to switch to lists though, given the support here!

**Comment by benjamin-hodgson** [comment]
I think with Brian's markup suggestion you can be back compat? Back of the envelope:

```less
ul.s-navigation, ol.s-navigation {
    .list-reset();
    li { .d-inline-block(); }
}
```

And all of the other CSS remains the same. You can deprecate the ability to use `s-navigation` on something other than a list but not drop it straight away

**Comment by benjamin-hodgson** [comment]
In fact, this seems to work right now:

```html
<nav>
    <ol class="list-reset s-navigation s-navigation__scroll s-navigation__muted">
        <li><a class="s-navigation--item">Link 1</a></li>
        <li><a class="s-navigation--item">Link 2</a></li>
        <li><a class="s-navigation--item">Link 3</a></li>
        <li><a class="s-navigation--item">Link 4</a></li>
    </ol>
</nav>
```

So I think the entire request is:

1. Add `.list-reset()` (or `:extend(.list-reset)` or whatever) to `ul.s-navigation`, `ol.s-navigation`
2. Update the docs to recommend the list version of the markup
3. Optionally port SO and Careers to use the list-y markup
