### ISSUE TITLE
Size classes for icons

### ISSUE THREAD

**Issue by bnickel** [StackExchange/Stacks#628]
Sometimes I have a pattern like:

```html
<div class="grid">
   <div class="grid--cell">@Svg.Something</div>
   <div class="grid--cell fl1">Content</div>
</div>

...

<div class="grid">
   <div class="grid--cell"></div>
   <div class="grid--cell fl1">Content</div>
</div>
```

I want the two content columns to line up even though the second `.grid` doesn't have an icon.

Normally, I could use a size class to fake things here but icons are 18px wide and size classes are a power of 2.  I can do either of the following but I don't like it:

```html
<div class="grid">
   <div class="grid--cell v-hidden">@Something</div> <!-- There but hidden -->
   <div class="grid--cell fl1">Content</div>
</div>

<div class="grid">
   <div class="grid--cell pl16 pr2"></div> <!-- Mathematical! -->
   <div class="grid--cell fl1">Content</div>
</div>
```

Could we get something like:

```
.w-icon { width: 18px !important; }
.h-icon { height: 18px !important; }
.w-icon-sm { width: 14px !important; }
.h-icon-sm { height: 14px !important; }
.w-icon-lg { width: 36px !important; }
.h-icon-lg { height: 36px !important; }
```

**Comment by aaronshekey** [comment]
Ah, interesting idea. I think I'm down! I don't love adding padding and such either.

My fear with this approach is I'm _constantly_ fighting with people adding arbitrary sizes to our icons. For example, `@Svg.Industry.With("w12 h12")`, this ends up as a blurry mess. Would this encourage people adding `@Svg.Industry.With("w-icon-sm h-icon-sm")` to these? They should be using `@Svg.IndustrySm` in both cases.

🤔

**Comment by bnickel** [comment]
We could add `@Svg.Empty`, `@Svg.EmptySm`,  `@Svg.EmptyLg` instead. 

Also, `Svg.IndustrySm` is 14x14, so there's no winning with that one 🙃.  You could make `With` assert if it has a size class in debug builds if you're desperate.

**Comment by aaronshekey** [comment]
> We could add `@Svg.Empty`, `@Svg.EmptySm`, `@Svg.EmptyLg` instead.

Interessstttinnnngggggggggggggggggggggggggggggggggggggggg

**Comment by aaronshekey** [comment]
hahah, Figma doesn't like empty components. Oops!

![image](https://user-images.githubusercontent.com/1369864/114228040-72054400-993b-11eb-9808-2842ef87c263.png)
