### ISSUE TITLE
Avatar text alignment is too low in Segoe

### ISSUE THREAD

**Issue by aaronshekey** [StackExchange/Stacks#676]
At the largest sizes, the line height in `s-avatar` needs to be finessed to account for Segoe's line-height differences.

![image](https://user-images.githubusercontent.com/1369864/120376097-145cfa80-c2e1-11eb-8a7f-5627fbd9f9f4.png)

**Comment by dancormier** [comment]
For posterity, here's `.s-avatar__128` with the existing `line-height: 1.45455` rendered in `--apple-system` and `Segoe UI` respectively:

# --apple-system
![20210601-154543](https://user-images.githubusercontent.com/647177/120381952-12029c80-c2f1-11eb-9569-e4db56a39153.png)

# Segoe UI
![20210601-154636](https://user-images.githubusercontent.com/647177/120382015-2777c680-c2f1-11eb-9d2a-2e2b37335c99.png)

**Comment by dancormier** [comment]
"Fixed" in #677 with a cool `line-height: 1.4;`
