### ISSUE TITLE
Icons in post summary are dependent on HTML whitespace

### ISSUE THREAD

**Issue by aaronshekey** [StackExchange/Stacks#686]
<img width="773" alt="screen_shot_2021-06-07_at_11 58 04_am" src="https://user-images.githubusercontent.com/1369864/121054664-32fc3f00-c782-11eb-8343-4b27dc06e327.png">
<img width="745" alt="screen_shot_2021-06-07_at_11 58 14_am" src="https://user-images.githubusercontent.com/1369864/121054694-398ab680-c782-11eb-8a59-0d7fbcb54710.png">

Removing the space before the 5 in Stacks docs reproduces the issue. Let's explicitly add some margins to those icons so we aren't relying on HTML whitespace.

**Comment by bnickel** [comment]
I would consider this by-design.

If we add margins, we'll end up with too much white-space in the most common case.  Outside of high volume views (🤢), I would never expect to see `<div>@Svg.CheckmarkSm@_s("#__count# answers")</div>`.  You'd more like see it with the space or even a line break.

This exact same situation is present in `<button class="s-btn s-btn__primary">@Svg.Shield @_s("Post your private question")</button>`.  If we remove that space it's too close.

**Comment by aaronshekey** [comment]
Closing based on @bnickel's points above. Folks will have to manage their own whitespace since there isn't a bulletproof way of doing it, especially in other languages.
