### ISSUE TITLE
Precentage-based min/max-width classes?

### ISSUE THREAD

**Issue by balpha** [StackExchange/Stacks#74]
Right now we have [atomic min/max-width classes](https://stackoverflow.design/base/width-height#max-width) only for some (seemingly arbitrary, although I assume there's reasoning behind them) fixed widths, with the exception of 100%.

Especially in a responsive world, percentage-based is something I need much more often than fixed values.

What do we think about adding those?

There would be a bit of naming discussions required. Right now `.wmx1` through `wmx12` refer to ~105px steps, while `.wmx100` refers to a percentage. So there's precedent for mixing "units" here.

Since a 10% min/max width is probably rarely helpful, we probably wouldn't have overlap if we go with, for example, `.wmx25`, `.wmx33`, `.wmx50`, `.wmx67`, `.wmx75`, or something like that.

Or we could be explicit like under my original suggestion for the naming scheme, e.g `.wmx-50pc` -- but we haven't done that anywhere else.

Any thoughts?

**Comment by ludwiczakpawel** [comment]
I'm all in for adding `.wmx25` (even starting with `.wmx20`) for percentage-based values. Also I'm not sure if we ever needed fixed pixel values for min/max-width, especially in cases where this could not be replaced with percentage values.
