### ISSUE TITLE
Typo in docs/_data/atomic-definitions.yml line 27

### ISSUE THREAD

**Issue by koide** [StackExchange/Stacks#75]
**Describe the bug**
A typo in the line 27 of said file

**To Reproduce**
Go https://stackoverflow.design/base/box-sizing, first table, first row, third column, says "browswer" instead of browser

**Expected behavior**
It saying "browser" instead

**Screenshots**
![imagen](https://user-images.githubusercontent.com/694364/42992595-46abd6da-8c09-11e8-938c-712dd14df071.png)

**Additional context**
Tried to PR, but no permission :-)

**Comment by TedGoas** [comment]
@koide Thanks for pointing this out, Vinko! I fixed this one. Let's fix your permissions so you can do this going forward. I'll ping someone in #stacks chat room.
