### ISSUE TITLE
Title snippets not correctly capitalized

### ISSUE THREAD

**Issue by TedGoas** [StackExchange/Stacks#77]
While working on the documentation site itself, I use a snippet like so:

`{% header {element: 'h2', text: 'When should I deviate from these guidelines?'} %}`

But it produces this 👇
<img width="926" alt="screen shot 2018-07-23 at 4 47 02 pm" src="https://user-images.githubusercontent.com/1172461/43102047-0da22f10-8e98-11e8-9b42-90aacf91e069.png">

---

The `i` should be uppercase, as it is in the snippet.

**Comment by aaronshekey** [comment]
I've noticed this! I'm sure I'm applying the wrong string operation somewhere inside `_plugins/header.rb` On it!
