### ISSUE TITLE
Support for responsive text sizing

### ISSUE THREAD

**Issue by Courtny** [StackExchange/Stacks#79]
**Problem**
Font sizes become unruly when responding to smaller screen size. This especially true at `sm` sizes where desktop sized headlines are visually too large for the layouts. Different scales work better for different screen sizes, and it's my hope Stacks can intelligently respond to this as a system.

**Solution I'd like**
It would be very useful to have some baked in responsive font scaling when hitting certain breakpoints. This could manifest itself as a Stacks baked in modular type scaling _(I explore this below)_ and/or the inclusion of some optional utility classes like `sm:text-smaller`, `sm:text-larger`. The utility classes would take the base font size for that type style and scale accordingly.

**Thoughts on calculating modular scaling**
On a small screen, heading sizes should probably be more uniform; a large screen has room for greater variation. We can use a modular typographic technique to fluidly transition between different scales. Maybe we could pick a ratio for small screens and a different ratio for large screens, and then work out the minimum and maximum font sizes for each heading level.

To calculate the modular scale, take the base font size and multiply it by the desired ratio to get larger numbers. For smaller numbers, divide. Repeat this process with subsequent results to get each required step in the scale:

**LARGER**

- 1em × 1.125em = 1.125em
- 1.125em × 1.125em = 1.266em
- 1.266em × 1.125em = 1.424em
- 1.424em × 1.125em = 1.602em

**SMALLER**

- 1em ÷ 1.125em = 0.889em
- 0.889em ÷ 1.125em = 0.790em
- 0.790em ÷ 1.125em = 0.702em
- 0.702em ÷ 1.125em = 0.624em

For this example, say we use 1.125 as our minimum scale and do the same calculations for 1.250 as our maximum scale. We’d then apply different steps in the scale to our heading levels.

- Minimum scale: 1.125
- Maximum scale: 1.250

Heading level | Minimum font size | Maximum font size
-- | -- | --
Heading 1 | 1.602em | 2.441em
Heading 2 | 1.424em | 1.953em
Heading 3 | 1.266em | 1.563em
Heading 4 | 1.125em | 1.250em

Using these numbers, perhaps there could be some Stacks definitions that deal with the initial scaling.

`fs-body1-min`
`fs-body1-max`

I'll try to put together a demonstration soon.

**Resources**
[Type Scale](http://type-scale.com)
[Modular Scale](http://www.modularscale.com/)

**Comment by aaronshekey** [comment]
This issue came out of a discussion we had at the end of a design critique. We'd like to avoid having a `sm:`, `md:`, and `lg:` override for each of our many font sizes. This approach would create sensible font resizing on the body, while allowing for more nuanced control while not requiring a huge new set of classes. :v: 

If you're up to it, this seems like a perfect thing to toss into a Codepen, @Courtny. Thanks for filing!
