### ISSUE TITLE
Accordion in sidebar widget breaks Chrome

### ISSUE THREAD

**Issue by ludwiczakpawel** [StackExchange/Stacks#80]
I've found weird bug when collapsing [accordion](https://stackoverflow.design/components/sidebar-widgets#accordions) panes in `.s-sidebarwidget` component. Chrome just freezes. Confirmed with bunch of folks. It works fine in Safari though.

**To Reproduce**
1. Go to [Sidebar Widget Accordions section](https://stackoverflow.design/components/sidebar-widgets#accordions).
2. Try to collapse pane.
3. Chrome freezes.

**Desktop:**
 - OS: macOS 10.13.4
 - Browser: Chrome 67.0.3396.99

**Comment by balpha** [comment]
Appears to have been a Chrome bug (sounds like it, too -- changing a CSS class should never freeze a browser) that was fixed in meantime. Paweł [confirmed](https://stackexchange.slack.com/archives/C27RWNQN9/p1534146421000048) he no longer sees the issue.
