### ISSUE TITLE
Component: Data Tables

### ISSUE THREAD

**Issue by TedGoas** [StackExchange/Stacks#81]
# Problem
[Our current tables](https://stackoverflow.design/components/tables) are don't support complex data sets out of the box. Alone, `s-table` is pretty barebones. Modifiers can be used to push text around, but there aren't codified patterns or recommendations for tables with more complex data. Eg. more than words, data that can be sorted or acted upon. We're currently going at it piecemeal and @UXPiper and I would like to not do that anymore.

# Proposal
Codify a few more patterns to support some use cases that we've come up against with more complex data tables.

## What to include:
- [ ] Improved column headers
- [ ] Sortable column headers
- [ ] Actions in table cells, and how to display them (eg. in a popover menu or not)
- [ ] Graphics in table cells (icons, badges, mini-graphs, etc.)
- [ ] Blank state ([related to this](https://5ad67b65e39e7c12b475dde8--stacks.netlify.com/components/blankslates))

## What _not_ to include:
* Title and text around the table.
* Search, sorting, and filtering
* Pagination, show more/less rows

---

Examples in the wild:

<img width="856" alt="screen shot 2018-07-26 at 12 22 21 pm" src="https://user-images.githubusercontent.com/1172461/43275778-c41631c6-90d0-11e8-8108-9dae148ce06b.png">

<img width="846" alt="screen shot 2018-07-26 at 12 21 57 pm" src="https://user-images.githubusercontent.com/1172461/43275792-cbfc118a-90d0-11e8-8ea9-58d3d035931e.png">

<img width="1045" alt="screen shot 2018-07-26 at 12 23 10 pm" src="https://user-images.githubusercontent.com/1172461/43275799-d3e93ab2-90d0-11e8-90c0-d054b3f03a30.png">

<img width="857" alt="screen shot 2018-07-26 at 12 31 40 pm" src="https://user-images.githubusercontent.com/1172461/43275803-d8cd33da-90d0-11e8-9b5e-2d0205ae7fa0.png">

**Comment by TedGoas** [comment]
@hellohynes @aaronshekey @UXPiper I created a branch for this... couple questions before I start.

1. Should we add this on to [the existing tables page](https://stackoverflow.design/components/tables)? I think _yes_, but am open if you think it should be it's own component.

2. What should we call these more complex tables?
[ ] Dashboard table
[ ] Data table (well _all_ tables are data tables)
[ ] Complex table
[ ] something else

**Comment by hellohynes** [comment]
Instead `s-table__simple` maybe explore classes that undid specific things, i.e. `s-table__borderless` removes all borders.

**Comment by UXPiper** [comment]
Adding code that I worked on to help replicate the complex code design. Hoping it's some assistance to @TedGoas 

`<table class="s-table bc-black-2 mt12 s-table__bordered fc-black-700">
            <thead class="bg-black-025 bt bc-black-2 fs-category">
                <tr>
                    <th scope="col" class="bc-black-2">@_s("Source")</th>
                    <th scope="col" class="bc-black-2" colspan="2">@_s("Job listing visits")</th>
                    <th scope="col" class="bc-black-2" colspan="2">@_s("% of total")</th>
                </tr>
            </thead>
            <tbody>
                @{ var maxClicks = Model.Referrers.Max(r => r.ClickCount);}
                @foreach (var referrer in Model.Referrers)
                {
                    var percentage = 100 * referrer.ClickCount / maxClicks;
                    <tr>
                        <td scope="row">@(string.IsNullOrEmpty(referrer.Url) ? _s("Direct URL or no referrer specified") : referrer.Url)</td>
                        <td class="ta-right brw0">@Localize.Numbers.CommaSeparated(referrer.ClickCount)</td>
                        <td class="va-middle blw0" width="116">
                            <div class="s-progress bg-white" id="brandprogress">
                                <div class="s-progress--bar bg-powder-400" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="@percentage" style="width: @percentage%"></div>
                            </div>
                        </td>
                        <td class="ta-right brw0 pr0">@Localize.Numbers.Percentage(referrer.Percentage)</td>
                        <td class="ps-relative blw0" width="38"><span class="d-inline-block ps-absolute" style="height:28px; width:28px; top: -2px;"><canvas class="js-pie-chart" data-percentage="@((int)Math.Ceiling(referrer.Percentage * 100))"></canvas></span></td>
                    </tr>
                }
            </tbody>
        </table>`

**Comment by TedGoas** [comment]
TBH I misread the comments above and started building classes _on top_ of `.s-table` instead of making `.s-table` The New Default and creating classes to undo things for simpler tables. My bad. I'll re-organized what I've done so far.

I did a quick search on Core for `.s-table` and found about 20-30 instances (and much of it looks recent), so I agree it's safe to change the default without worry too much about breaking something in the wild.
