### ISSUE TITLE
Add aria roles for `s-tooltip`

### ISSUE THREAD

**Issue by aaronshekey** [StackExchange/Stacks#839]
When our tooltips are available, we take the `title` attribute, remove it, and use its content to build the tooltip. We do this so we don't get the browser tooltips while viewing the custom popover, but we should probably replace this with `aria-label` while the popover is shown?

Additionally, there seems to be certain scenarios where the tooltip is stuck with `aria-hidden="true"` which seems like the opposite of what we'd like.

**Comment by dancormier** [comment]
✅
