### ISSUE TITLE
Can we standardize how we're using s-notice in the docs site?

### ISSUE THREAD

**Issue by TedGoas** [StackExchange/Stacks#89]
We have a few different styles.

<img width="649" alt="screen shot 2018-08-02 at 10 42 59 am" src="https://user-images.githubusercontent.com/1172461/43591289-03e43008-9641-11e8-831d-ee9f6f252882.png">

This ☝️ looks good, but it and it's children are styled using utility classes. When someone changes the style, it doesn't cascade to the others.

Would be nice to have one or two parent classes that take care of everything inside and "just work." I'd love not to have to think about this.

**Comment by hellohynes** [comment]
I'm not understanding the problem @TedGoas. You can provide some problem examples?

**Comment by TedGoas** [comment]
@hellohynes We have [a few notice styles](https://stackoverflow.design/components/notices). Here's another one from the docs site:

<img width="648" alt="screen shot 2018-08-02 at 10 58 11 am" src="https://user-images.githubusercontent.com/1172461/43593015-cf89dc14-9644-11e8-9a59-4bc96f507d9a.png">

---

Let's agree we won't use the outline style here anymore. 👍

Looking at the power blue example, here's the code:

```
<div class="grid ai-start gs4 s-notice s-notice__info mb48">
    <div class="grid--cell mr8">{% svg /resources/svg-icons/Alert.svg width="18" height="18" aria-hidden="true" class="svg-icon iconAlert" %}</div>
    <div class="grid--cell lh-lg">
        <strong>Note:</strong> The <code class="stacks-code bg-powder-200">unset</code> property is a combination property that resets a property to its inherited value. It behaves like the <code class="stacks-code bg-powder-200">inherit</code> and the <code class="stacks-code bg-powder-200">initial</code> keywords, but it properly selects the right value for you. Unfortunately, <code class="stacks-code bg-powder-200">unset</code> is not fully supported in Internet Explorer. Because of this all <code class="stacks-code bg-powder-200">unset</code> values have the correct <code class="stacks-code bg-powder-200">inherit</code> or <code class="stacks-code bg-powder-200">initial</code> value applied.
    </div>
</div>
```

There's some utility classes in there I think we can remove, or rather, _move_. Classes like `mr8`, `lh-lg`, and `bg-powder-200`. I'm suggesting we move stuff like this into a higher level class so we don't have to inline style each individual notice.

**Comment by hellohynes** [comment]
I don't agree that we should not use outlined style on the Stacks site. It's a Stacks style.

Going through the utility classes…

 - You don't need `mr8` on `grid-cell`. Use `gs8` on the wrapping `grid` and you get the same effect
 - Add `lh-lg` to the wrapping `s-notice`
 - Unfortunately if you want to change the background color on `stacks-code` you will have to apply a different class. What's the problem using the default gray background?

**Comment by TedGoas** [comment]
@hellohynes FWIW [that isn't my code](https://github.com/StackExchange/Stacks/blob/develop/docs/_includes/notice-unset.html).

I'm suggesting we standardize the default style because we're currently styling each of them inline and it's not scaling well (I have to redo a bunch of notices that should match but don't).
