### ISSUE TITLE
Stop using "important!" when possible

### ISSUE THREAD

**Issue by 89z** [StackExchange/Stacks#891]
<https://github.com/StackExchange/Stacks/blob/7a69c49ec443d85d859a25b2b86c0da7292adbce/lib/css/atomic/_stacks-misc.less#L195-L203>

These type declarations are bad practice. Some people want to override a style, like unsticking the top bar:

https://meta.stackexchange.com/a/369069

normally this can be done with tools such as Stylus, in one of three ways:

1. If site is not styling the item, then user can just add any declaration

2. If site is already styling the item, then user can override with `important!`

3. If site is already styling the item, and already using `important!`, then user is forced to also use `important!`, AND use a more specific selector in order to override the site styling

If its not obvious already, option three (the one that's currently be used by Stacks) is the most user hostile. Not only have you removed any UI option to disable stickiness, but you made it as difficult as possible to override. Please fix this.

**Comment by b-kelly** [comment]
As much as we'd _love_ to stop using `!important`, that's unfortunately not a reality for us at the moment. One of the original reasons we used this approach was because we were outfitting a legacy codebase with lots of intrusive preexisting styles. The situation has vastly improved due to a near 100% adoption of Stacks, but lots of legacy styles still remain.

One day we'll get there, but until then, we're mostly stuck with the approach we have.

**Comment by 89z** [comment]
Regardless of your comment, you closing the issue signals that this issue is not even important enough to remember. As with the issue being closed, being forgotten is exactly what will happen. If that's your intention, then you don't need to do anything more.

However if you actually care to see this fixed at some point in the future, I would recommend reopening.

**Comment by 89z** [comment]
Regardless of your comment, you closing the issue signals that this issue is not even important enough to remember. As with the issue being closed, being forgotten is exactly what will happen. If that's your intention, then you don't need to do anything more.

However if you actually care to see this fixed at some point in the future, I would recommend reopening.
