### ISSUE TITLE
@black-500 color values in table

### ISSUE THREAD

**Issue by ludwiczakpawel** [StackExchange/Stacks#92]
There's some inconsistency in color values for `@black-500` color in [that table](https://stackoverflow.design/product/base/colors#black).

- Little square on the left returns hex value `#6A737C`. It's coming from`.bg-black-500` class so I assume it's correct.
- HEX value in table is `#6A7E7C` – it should be `3` instead of `E`.
- RGB value in table is `108,115,112` – it should be `106,115,124`. It's weird because it's different from original value and also from corrupted value in HEX column.

I haven't noticed that in other colors. But I'm not sure if those values were entered manually or generated with some magic in backend/js. But if it's latter then more colors might be corrupted.

**Comment by ludwiczakpawel** [comment]
Update:

I've noticed that RGB values are wrong in most of the blacks. On the other hand, blues are fine. So I'm not sure what's the cause of this bug.

**Comment by aaronshekey** [comment]
Mathematically, I like the idea of our colors being generated, but in practice, it just doesn't create a proper visual gradation. I'm 👍 on basing these on hand-picked, visually selected hex values.
