### ISSUE TITLE
We should package up Stacks email templates

### ISSUE THREAD

**Issue by aaronshekey** [StackExchange/Stacks#93]
Following a conversation with an internal dev, I think we should be bundling our email templates into a package and versioning them properly. This way devs can add Stacks email as a dependency and receive the correct template. I'm happy to set this up, so I've assigned it to myself.

If this doesn't make any sense, let's talk about it.

**Comment by TedGoas** [comment]
Let's chat! I'd like to understand how this would be used, who might work this way, and what (if anything) we need to do to support this going forward..

**Comment by aaronshekey** [comment]
This was discussed in our weekly meeting and it was decided that since our templates aren't delivered as a single artifact, wrapping them up in a package doesn't make sense right now.
