### ISSUE TITLE
Email: tidy up .s-tag

### ISSUE THREAD

**Issue by TedGoas** [StackExchange/Stacks#98]
The [preview of `.s-tag`](https://stackoverflow.design/email/components#tags) is pulling in a border-radius defined in Stacks web css, but currently tags don't have a border-radius in email. We should either:

1. Add border radius to email, or
2. Remove the border-radius from the preview.

**Comment by ludwiczakpawel** [comment]
I'd vote for adding border radius, especially we've just added it to so.com.
